version: 2

builds:
  - main: ./cmd/mg
    binary: mg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: matt-wright86
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/quietpublish/mardi-gras"
    description: "Terminal UI for Beads issue tracking — your issues deserve a parade"
    license: "MIT"
    install: |
      bin.install "mg"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  header: |
    ## What's New

    Install or upgrade:

    ```bash
    # Homebrew
    brew install matt-wright86/homebrew-tap/mardi-gras
    brew upgrade mardi-gras

    # Go
    go install github.com/matt-wright86/mardi-gras/cmd/mg@{{ .Tag }}
    ```
  footer: |
    ---
    _Let the good tasks roll._ ⚜
