// Package gcclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package gcclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetV0CityByCityNameAgentsParamsRunning.
const (
	False GetV0CityByCityNameAgentsParamsRunning = "false"
	True  GetV0CityByCityNameAgentsParamsRunning = "true"
)

// Valid indicates whether the value is a known member of the GetV0CityByCityNameAgentsParamsRunning enum.
func (e GetV0CityByCityNameAgentsParamsRunning) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// AgentResponse defines model for AgentResponse.
type AgentResponse struct {
	ActiveBead        *string      `json:"active_bead,omitempty"`
	Activity          *string      `json:"activity,omitempty"`
	Available         bool         `json:"available"`
	ContextPct        *int64       `json:"context_pct,omitempty"`
	ContextWindow     *int64       `json:"context_window,omitempty"`
	Description       *string      `json:"description,omitempty"`
	DisplayName       *string      `json:"display_name,omitempty"`
	LastOutput        *string      `json:"last_output,omitempty"`
	Model             *string      `json:"model,omitempty"`
	Name              string       `json:"name"`
	Pool              *string      `json:"pool,omitempty"`
	Provider          *string      `json:"provider,omitempty"`
	Rig               *string      `json:"rig,omitempty"`
	Running           bool         `json:"running"`
	Session           *SessionInfo `json:"session,omitempty"`
	State             string       `json:"state"`
	Suspended         bool         `json:"suspended"`
	UnavailableReason *string      `json:"unavailable_reason,omitempty"`
}

// CityInfo defines model for CityInfo.
type CityInfo struct {
	Error           *string   `json:"error,omitempty"`
	Name            string    `json:"name"`
	Path            string    `json:"path"`
	PhasesCompleted *[]string `json:"phases_completed,omitempty"`
	Running         bool      `json:"running"`
	Status          *string   `json:"status,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// ListBodyAgentResponse defines model for ListBodyAgentResponse.
type ListBodyAgentResponse struct {
	// Items The list of items.
	Items *[]AgentResponse `json:"items"`

	// NextCursor Cursor for the next page of results.
	NextCursor *string `json:"next_cursor,omitempty"`

	// Partial True when one or more backends failed and the list is incomplete.
	Partial *bool `json:"partial,omitempty"`

	// PartialErrors Human-readable errors from backends that failed during aggregation.
	PartialErrors *[]string `json:"partial_errors,omitempty"`

	// Total Total number of items matching the query.
	Total int64 `json:"total"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	Attached     bool       `json:"attached"`
	LastActivity *time.Time `json:"last_activity,omitempty"`
	Name         string     `json:"name"`
}

// StatusAgentCounts defines model for StatusAgentCounts.
type StatusAgentCounts struct {
	// Quarantined Number of quarantined agents.
	Quarantined int64 `json:"quarantined"`

	// Running Number of running agents.
	Running int64 `json:"running"`

	// Suspended Number of suspended agents.
	Suspended int64 `json:"suspended"`

	// Total Total number of agents.
	Total int64 `json:"total"`
}

// StatusAgentDetail defines model for StatusAgentDetail.
type StatusAgentDetail struct {
	// Draining True when the pool is draining this instance.
	Draining *bool `json:"draining,omitempty"`

	// Expanded True when this row is a pool-expanded instance (renderer indents differently).
	Expanded *bool `json:"expanded,omitempty"`

	// GroupName Pool group label for expanded rows; same as QualifiedName for singletons.
	GroupName *string `json:"group_name,omitempty"`

	// Name Unqualified agent name (for pool instances, the per-instance short name like 'polecat-1').
	Name string `json:"name"`

	// QualifiedName Rig-qualified name when applicable, else the bare agent name.
	QualifiedName string `json:"qualified_name"`

	// Running Observed running state of the agent's session.
	Running bool `json:"running"`

	// ScaleLabel 'scaled (min=N, max=M)' header emitted once per pool group.
	ScaleLabel *string `json:"scale_label,omitempty"`

	// Scope city or rig.
	Scope string `json:"scope"`

	// SessionName tmux session name CLI drain-ops key on.
	SessionName *string `json:"session_name,omitempty"`

	// Suspended Whether the agent (or its rig) is suspended.
	Suspended bool `json:"suspended"`
}

// StatusBody defines model for StatusBody.
type StatusBody struct {
	// AgentCount Total agent count (deprecated, use agents.total).
	AgentCount int64 `json:"agent_count"`

	// AgentDetails Per-agent state (for CLI status views). Empty when none.
	AgentDetails *[]StatusAgentDetail `json:"agent_details,omitempty"`
	Agents       StatusAgentCounts    `json:"agents"`
	Mail         StatusMailCounts     `json:"mail"`

	// Name City name.
	Name string `json:"name"`

	// NamedSessionDetails Per-named-session detail. Empty when none configured.
	NamedSessionDetails *[]StatusNamedSessionDetail `json:"named_session_details,omitempty"`

	// Partial True when one or more status backing reads returned incomplete data.
	Partial *bool `json:"partial,omitempty"`

	// PartialErrors Human-readable errors from incomplete status backing reads.
	PartialErrors *[]string `json:"partial_errors,omitempty"`

	// Path City directory path.
	Path string `json:"path"`

	// RigCount Total rig count (deprecated, use rigs.total).
	RigCount int64 `json:"rig_count"`

	// RigDetails Per-rig detail (for CLI status views). Empty when none.
	RigDetails *[]StatusRigDetail `json:"rig_details,omitempty"`
	Rigs       StatusRigCounts    `json:"rigs"`

	// Running Number of running agent processes.
	Running             int64                      `json:"running"`
	SessionCountsDetail *StatusSessionCountsDetail `json:"session_counts_detail,omitempty"`
	StoreHealth         *StatusStoreHealth         `json:"store_health,omitempty"`

	// Suspended Whether the city is suspended.
	Suspended bool `json:"suspended"`

	// UptimeSec Server uptime in seconds.
	UptimeSec int64 `json:"uptime_sec"`

	// Version Server version.
	Version *string          `json:"version,omitempty"`
	Work    StatusWorkCounts `json:"work"`
}

// StatusMailCounts defines model for StatusMailCounts.
type StatusMailCounts struct {
	// Total Total number of messages.
	Total int64 `json:"total"`

	// Unread Number of unread messages.
	Unread int64 `json:"unread"`
}

// StatusNamedSessionDetail defines model for StatusNamedSessionDetail.
type StatusNamedSessionDetail struct {
	// Identity Qualified named-session identity.
	Identity string `json:"identity"`

	// Mode Named-session mode (on-demand, always, etc.).
	Mode string `json:"mode"`

	// Status Lifecycle status string (materialized, reserved-unmaterialized, etc.).
	Status string `json:"status"`
}

// StatusRigCounts defines model for StatusRigCounts.
type StatusRigCounts struct {
	// Suspended Number of suspended rigs.
	Suspended int64 `json:"suspended"`

	// Total Total number of rigs.
	Total int64 `json:"total"`
}

// StatusRigDetail defines model for StatusRigDetail.
type StatusRigDetail struct {
	// Name Rig name.
	Name string `json:"name"`

	// Path Rig directory path.
	Path string `json:"path"`

	// Suspended Whether the rig is suspended (either explicitly or because all its agents are suspended).
	Suspended bool `json:"suspended"`
}

// StatusSessionCountsDetail defines model for StatusSessionCountsDetail.
type StatusSessionCountsDetail struct {
	// Active Number of active sessions.
	Active int64 `json:"active"`

	// Suspended Number of suspended sessions.
	Suspended int64 `json:"suspended"`
}

// StatusStoreHealth defines model for StatusStoreHealth.
type StatusStoreHealth struct {
	// LastGcAt RFC3339 timestamp of last maintenance run.
	LastGcAt *string `json:"last_gc_at,omitempty"`

	// LastGcStatus Status of last maintenance run ('success' or 'failed').
	LastGcStatus *string `json:"last_gc_status,omitempty"`

	// LiveRows Live bead row count.
	LiveRows int64 `json:"live_rows"`

	// Path On-disk path of the Dolt store.
	Path string `json:"path"`

	// RatioMbPerRow Derived megabytes per row.
	RatioMbPerRow float64 `json:"ratio_mb_per_row"`

	// SizeBytes Total bytes of the store directory.
	SizeBytes int64 `json:"size_bytes"`

	// ThresholdMbPerRow Ratio threshold; a ratio above this trips warning.
	ThresholdMbPerRow float64 `json:"threshold_mb_per_row"`

	// Warning True when maintenance is overdue.
	Warning bool `json:"warning"`
}

// StatusWorkCounts defines model for StatusWorkCounts.
type StatusWorkCounts struct {
	// InProgress Number of in-progress work items.
	InProgress int64 `json:"in_progress"`

	// Open Number of open work items.
	Open int64 `json:"open"`

	// Ready Number of ready work items.
	Ready int64 `json:"ready"`
}

// SupervisorCitiesOutputBody defines model for SupervisorCitiesOutputBody.
type SupervisorCitiesOutputBody struct {
	// Items Managed cities with status info.
	Items *[]CityInfo `json:"items"`

	// Total Total count.
	Total int64 `json:"total"`
}

// GetV0CityByCityNameAgentsParams defines parameters for GetV0CityByCityNameAgents.
type GetV0CityByCityNameAgentsParams struct {
	// Index Event sequence number; when provided, blocks until a newer event arrives.
	Index *string `form:"index,omitempty" json:"index,omitempty"`

	// Wait How long to block waiting for changes (Go duration string, e.g. 30s). Default 30s, max 2m.
	Wait *string `form:"wait,omitempty" json:"wait,omitempty"`

	// Pool Filter by pool name.
	Pool *string `form:"pool,omitempty" json:"pool,omitempty"`

	// Rig Filter by rig name.
	Rig *string `form:"rig,omitempty" json:"rig,omitempty"`

	// Running Filter by running state. Omit to return all agents.
	Running *GetV0CityByCityNameAgentsParamsRunning `form:"running,omitempty" json:"running,omitempty"`

	// Peek Include last output preview.
	Peek *bool `form:"peek,omitempty" json:"peek,omitempty"`
}

// GetV0CityByCityNameAgentsParamsRunning defines parameters for GetV0CityByCityNameAgents.
type GetV0CityByCityNameAgentsParamsRunning string

// GetV0CityByCityNameStatusParams defines parameters for GetV0CityByCityNameStatus.
type GetV0CityByCityNameStatusParams struct {
	// Index Event sequence number; when provided, blocks until a newer event arrives.
	Index *string `form:"index,omitempty" json:"index,omitempty"`

	// Wait How long to block waiting for changes (Go duration string, e.g. 30s). Default 30s, max 2m.
	Wait *string `form:"wait,omitempty" json:"wait,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV0Cities request
	GetV0Cities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV0CityByCityNameAgents request
	GetV0CityByCityNameAgents(ctx context.Context, cityName string, params *GetV0CityByCityNameAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV0CityByCityNameStatus request
	GetV0CityByCityNameStatus(ctx context.Context, cityName string, params *GetV0CityByCityNameStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV0Cities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV0CitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV0CityByCityNameAgents(ctx context.Context, cityName string, params *GetV0CityByCityNameAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV0CityByCityNameAgentsRequest(c.Server, cityName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV0CityByCityNameStatus(ctx context.Context, cityName string, params *GetV0CityByCityNameStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV0CityByCityNameStatusRequest(c.Server, cityName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV0CitiesRequest generates requests for GetV0Cities
func NewGetV0CitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/cities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV0CityByCityNameAgentsRequest generates requests for GetV0CityByCityNameAgents
func NewGetV0CityByCityNameAgentsRequest(server string, cityName string, params *GetV0CityByCityNameAgentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cityName", cityName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/city/%s/agents", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Index != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "index", *params.Index, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Wait != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "wait", *params.Wait, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Pool != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "pool", *params.Pool, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Rig != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "rig", *params.Rig, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Running != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "running", *params.Running, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Peek != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "peek", *params.Peek, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV0CityByCityNameStatusRequest generates requests for GetV0CityByCityNameStatus
func NewGetV0CityByCityNameStatusRequest(server string, cityName string, params *GetV0CityByCityNameStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cityName", cityName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/city/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Index != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "index", *params.Index, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Wait != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "wait", *params.Wait, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV0CitiesWithResponse request
	GetV0CitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV0CitiesResponse, error)

	// GetV0CityByCityNameAgentsWithResponse request
	GetV0CityByCityNameAgentsWithResponse(ctx context.Context, cityName string, params *GetV0CityByCityNameAgentsParams, reqEditors ...RequestEditorFn) (*GetV0CityByCityNameAgentsResponse, error)

	// GetV0CityByCityNameStatusWithResponse request
	GetV0CityByCityNameStatusWithResponse(ctx context.Context, cityName string, params *GetV0CityByCityNameStatusParams, reqEditors ...RequestEditorFn) (*GetV0CityByCityNameStatusResponse, error)
}

type GetV0CitiesResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *SupervisorCitiesOutputBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetV0CitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV0CitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetV0CitiesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetV0CityByCityNameAgentsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ListBodyAgentResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetV0CityByCityNameAgentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV0CityByCityNameAgentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetV0CityByCityNameAgentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetV0CityByCityNameStatusResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *StatusBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetV0CityByCityNameStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV0CityByCityNameStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetV0CityByCityNameStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetV0CitiesWithResponse request returning *GetV0CitiesResponse
func (c *ClientWithResponses) GetV0CitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV0CitiesResponse, error) {
	rsp, err := c.GetV0Cities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV0CitiesResponse(rsp)
}

// GetV0CityByCityNameAgentsWithResponse request returning *GetV0CityByCityNameAgentsResponse
func (c *ClientWithResponses) GetV0CityByCityNameAgentsWithResponse(ctx context.Context, cityName string, params *GetV0CityByCityNameAgentsParams, reqEditors ...RequestEditorFn) (*GetV0CityByCityNameAgentsResponse, error) {
	rsp, err := c.GetV0CityByCityNameAgents(ctx, cityName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV0CityByCityNameAgentsResponse(rsp)
}

// GetV0CityByCityNameStatusWithResponse request returning *GetV0CityByCityNameStatusResponse
func (c *ClientWithResponses) GetV0CityByCityNameStatusWithResponse(ctx context.Context, cityName string, params *GetV0CityByCityNameStatusParams, reqEditors ...RequestEditorFn) (*GetV0CityByCityNameStatusResponse, error) {
	rsp, err := c.GetV0CityByCityNameStatus(ctx, cityName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV0CityByCityNameStatusResponse(rsp)
}

// ParseGetV0CitiesResponse parses an HTTP response from a GetV0CitiesWithResponse call
func ParseGetV0CitiesResponse(rsp *http.Response) (*GetV0CitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV0CitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SupervisorCitiesOutputBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetV0CityByCityNameAgentsResponse parses an HTTP response from a GetV0CityByCityNameAgentsWithResponse call
func ParseGetV0CityByCityNameAgentsResponse(rsp *http.Response) (*GetV0CityByCityNameAgentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV0CityByCityNameAgentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListBodyAgentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetV0CityByCityNameStatusResponse parses an HTTP response from a GetV0CityByCityNameStatusWithResponse call
func ParseGetV0CityByCityNameStatusResponse(rsp *http.Response) (*GetV0CityByCityNameStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV0CityByCityNameStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StatusBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
