// Package gcclient is the generated HTTP client for the Gas City Supervisor
// API (https://docs.gascityhall.com/reference/api).
//
// client_gen.go is machine-generated by oapi-codegen from the pinned spec in
// openapi.json (gascity tag v1.2.1). Do not edit it by hand. To regenerate
// after bumping the spec, run `make gc-client` from the repo root — it
// downgrades the 3.1 spec to 3.0 (via downgrade.jq) because oapi-codegen does
// not yet fully support OpenAPI 3.1, then runs oapi-codegen with config.yaml.
//
// Generation is scoped (config.yaml `include-operation-ids`) to the endpoints
// mg consumes; widen that list as later phases add mutations.
package gcclient
